<a href="https://colab.research.google.com/github/luttism/Bootcamp_data_science/blob/main/modulo01_aula01_desafio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aula 01 - Bootcamp - Data Science - Alura**
------

1) Obteve os dados do banco de dados "Datasus" gerado no Tabnet - Gastos de Ambiente hospitalar pelo Governo Brasileiro - a partir de 2008. Os dados foram exportados no format "csv" (comma-separated-values).

2) Importar os dados usando a biblioteca do Python chamada "pandas" com alias "pd":

In [2]:
import pandas as pd

dados = pd.read_csv("/content/A151346189_28_143_208.csv", encoding="ISO-8859-1", 
                    skiprows = 3, sep=";", skipfooter=12, thousands=".", decimal=",")
#mostra as 5 primeiras linhas do dataframe "dados"
dados.head()

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.

  Unidade da Federação     2008/Jan  ...     2020/Ago         Total
0          11 Rondônia   1388528.39  ...  10285455.78  9.291297e+08
1              12 Acre    902416.00  ...            -  4.206680e+08
2          13 Amazonas   4735529.42  ...  14726443.67  1.771655e+09
3           14 Roraima    657889.53  ...   2826486.18  3.050109e+08
4              15 Pará  18864744.11  ...  39911193.02  4.437116e+09

[5 rows x 154 columns]

3) Formatar os dados para duas casas decimais, pois, por "default" é mostrado em notação científica.

In [3]:
pd.options.display.float_format = "{:.2f}".format

4) Desafio da aula 01: selecionar somente os valores de Janeiro de 2008?
Levando em consideração que é um dataframe, encontro a seguinte solução:

In [19]:
dados[["Unidade da Federação", "2008/Jan"]]

      Unidade da Federação    2008/Jan
0              11 Rondônia  1388528.39
1                  12 Acre   902416.00
2              13 Amazonas  4735529.42
3               14 Roraima   657889.53
4                  15 Pará 18864744.11
5                 16 Amapá  1120973.34
6             17 Tocantins  3441592.69
7              21 Maranhão 10723506.39
8                 22 Piauí  7985142.43
9                 23 Ceará 15539821.90
10  24 Rio Grande do Norte  5947814.08
11              25 Paraíba 10723002.45
12           26 Pernambuco 14393949.89
13              27 Alagoas  6243726.32
14              28 Sergipe  2780750.11
15                29 Bahia 21211522.47
16         31 Minas Gerais 45671659.76
17       32 Espírito Santo  5456723.98
18       33 Rio de Janeiro 23025258.52
19            35 São Paulo 91678473.48
20               41 Paraná 38266347.46
21       42 Santa Catarina 16504913.45
22    43 Rio Grande do Sul 30931325.46
23   50 Mato Grosso do Sul  5377392.11
24          51 Mato Grosso  4795299.01
25                52 Goiás 15310637.29
26     53 Distrito Federal  4745919.19

In [20]:
#média do mês de Janeiro
dados["2008/Jan"].mean()

15126846.638148146